title: ReviewQ
description: My very nice blog
author: "Stuart Wooodward"

theme: minima

base_url: reviewq/
repository: stuart-labs/reviewqhttp

# Minima social links
github_username: stuartcw
linkedin_username: stuartcw
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
  - _pages/topic_index.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

collections:
  topics:
    output: true
    permalink: /:collection/:path/
